# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:47:58+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ConvertcurrencyGetResponse(BaseModel):
    Code: Optional[str] = None
    Converted: Optional[str] = None
    Credits: Optional[str] = None
    Currency: Optional[str] = None
